<!-- sidebar navigation -->
<nav id="mySideNav" class="sidenav">
  <div class="closebtn" onclick="closeNav()">
    <a href="Index.php"><img id="sidebarLogo" src="images/bazaar-logo.jpg" alt="Bazaar ceramics company logo"></a>&times;
  </div>
    <a href="Index.php" class="sidebarHome sidebarCurrent">Home</a>
    <a href="#" class="dropdown">About Us<span class="downArrow">&darr;</span></a>
  <div class="dropdown-container">
    <a href="HTML/company_bg.php">Company Background</a>
    <a href="HTML/company_mission.php">Mission Statement</a>
  </div>
    <a href="#" class="dropdown">Design & Production<span class="downArrow">&darr;</span></a>
  <div class="dropdown-container">
    <a href="HTML/underConstruction.php">Design Process</a>
    <a href="HTML/production_process.php">Production Process</a>
  </div>
    <a href="HTML/members_page.php">Members</a>
    <a href="#" class="dropdown">Offline Orders<span class="downArrow">&darr;</span></a>
  <div class="dropdown-container">
    <a href="HTML/underConstruction.php">Non-account Order Form</a>
    <a href="HTML/underConstruction.php">Account Order Form</a>
  </div>
    <a href="HTML/underConstruction.php">Contact Us</a>
</nav>